---
# Base playbook for ubuntu
- name: Base
  user: ubuntu
  sudo: True
  tags: base
  connection: local
  hosts: all
  tasks:
    - name: copy the awx 13 tarball
      get_url: url=http://ansibleworks.com/releases/awx/setup/awx-setup-1.3.0.tar.gz dest=/opt

    - name: untar the ball
      shell: chdir=/opt tar -xvzf awx-setup-1.3.0.tar.gz

    - name: create teh directory
      file: path=/run/lock state=directory mode=0775

    - name: start rysyslog
      service: name=rsyslog state=started
      ignore_errors: true

    - name: install the tarball
      shell: chdir=/opt/awx-setup-1.3.0 ./setup.sh

    - name: servie stop
      service: name={{ item }} state=stopped
      with_items:
       - postgresql
       - apache2
       - supervisor
       - rsyslog

    - name: kill procs
      shell: killall -9 awx-manage
      ignore_errors: yes


